/**
 * Central Hugeicons surface for the application and shared UI components.
 *
 * Nothing imports `@hugeicons/*` anywhere else — the aliases below are the
 * product's vocabulary and this file is the only place a name is bound to a
 * glyph, so swapping icon sets stays a one-file change. The names are inherited
 * from the lucide barrel this replaced; where Hugeicons had no twin the nearest
 * glyph was hand-picked (ChevronsUpDown -> ArrowUpDown, LifeBuoy -> Lifebuoy,
 * Trash2 -> Trash, and the numbered variants: Clock01, Search01, Settings01,
 * Table01, Sun01, Upload01, Download01, Wallet01, Home01, Building02).
 *
 * Hugeicons ships glyph *data* plus one renderer, where lucide shipped a
 * component per glyph, so an icon reads `<Icon icon={CheckIcon} class="size-4" />`.
 * Everything exported here is data; `Icon` is the only component.
 */
export { default as Icon } from "./icon.svelte";
export type { IconGlyph } from "./icon.svelte";

export {
  AccessibilityIcon as Accessibility,
  FileTextIcon as AiFile,
  ArchiveIcon as Archive,
  ArchiveXIcon as ArchiveOff,
  ArchiveRestoreIcon as ArchiveRestore,
  ArrowDown01Icon as ArrowDownIcon,
  ArrowLeft01Icon as ArrowLeft,
  ArrowUp01Icon as ArrowUp,
  ArrowUpRight01Icon as ArrowUpRight,
  BellIcon as Bell,
  Building02Icon as Building2,
  PanelsTopLeftIcon as Cabinet,
  CalculatorIcon as Calculator,
  CalendarRangeIcon as CalendarRange,
  CheckIcon as Check,
  CircleCheckIcon as CheckCircle2,
  CheckIcon,
  ChevronDownIcon as ChevronDown,
  ChevronDownIcon,
  ChevronLeftIcon as ChevronLeft,
  ChevronRightIcon as ChevronRight,
  ChevronRightIcon,
  ArrowUpDownIcon as ChevronsUpDown,
  ChevronUpIcon as ChevronUp,
  ChevronUpIcon,
  AlertCircleIcon as CircleAlert,
  CircleCheckIcon as CircleCheck,
  CircleCheckIcon,
  CircleDashedIcon as CircleDashed,
  CircleDotIcon as CircleDot,
  HelpCircleIcon as CircleHelp,
  CircleSlashIcon as CircleSlash,
  Clock01Icon as Clock,
  CopyIcon as Copy,
  CornerDownLeftIcon as CornerDownLeft,
  Download01Icon as Download,
  EyeIcon as Eye,
  EyeOffIcon as EyeOff,
  FileCodeIcon as FileCode2,
  FileQuestionMarkIcon as FileQuestionMark,
  FileSpreadsheetIcon as FileSpreadsheet,
  FileTextIcon as FileText,
  FilterIcon as Filter,
  HammerIcon as Hammer,
  HardHatIcon as HardHat,
  HeadsetIcon as Headset,
  HistoryIcon as History,
  Home01Icon as House,
  ImagePlusIcon as ImagePlus,
  InboxIcon as Inbox,
  InfoIcon,
  KanbanIcon as Kanban,
  KeyRoundIcon as KeyRound,
  LanguagesIcon as Languages,
  LayoutDashboardIcon as LayoutDashboard,
  LifebuoyIcon as LifeBuoy,
  ListChecksIcon as ListChecks,
  ListIcon as ListView,
  LoaderCircleIcon as Loader2,
  LoaderCircleIcon as Loader2Icon,
  LockIcon as Lock,
  LogOutIcon as LogOut,
  MenuIcon as Menu,
  MessageSquareIcon as MessageSquare,
  MinusIcon,
  MoonIcon as Moon,
  EllipsisIcon as MoreHorizontal,
  MousePointerClickIcon as MousePointerClick,
  OctagonXIcon as OctagonX,
  OctagonXIcon,
  PaletteIcon as Palette,
  PanelLeftIcon as PanelLeft,
  PanelRightIcon as PanelRight,
  PaperclipIcon as Paperclip,
  PauseCircleIcon as PauseCircle,
  PencilIcon as Pencil,
  PlayCircleIcon as PlayCircle,
  PlusIcon as Plus,
  RefreshCwIcon as RefreshCw,
  RotateCcwIcon as RotateCcw,
  SaveIcon as Save,
  ScaleIcon as Scale,
  Search01Icon as Search,
  SearchXIcon as SearchX,
  SendIcon as Send,
  Settings01Icon as Settings,
  ShieldMinusIcon as ShieldMinus,
  ShieldPlusIcon as ShieldPlus,
  SlidersHorizontalIcon as SlidersHorizontal,
  SparklesIcon as Sparkles,
  Sun01Icon as Sun,
  Table01Icon as Table2,
  TrashIcon as Trash2,
  TrendingUpIcon as TrendingUp,
  TriangleAlertIcon as TriangleAlert,
  TriangleAlertIcon,
  Upload01Icon as Upload,
  UserPlusIcon as UserPlus,
  UserRoundIcon as UserRound,
  UsersIcon as Users,
  Wallet01Icon as Wallet,
  XIcon as X,
  XIcon,
} from "@hugeicons/core-free-icons";
