/** Central Lucide icon surface for the application and shared UI components. */
import type { Accessibility as AccessibilityIcon } from "lucide-svelte";

export type { IconProps } from "lucide-svelte";
export type IconComponent = typeof AccessibilityIcon;

export {
  Accessibility,
  FileText as AiFile,
  Archive,
  ArchiveX as ArchiveOff,
  ArchiveRestore,
  ArrowDown as ArrowDownIcon,
  ArrowLeft,
  ArrowUpRight,
  Bell,
  Building2,
  PanelsTopLeft as Cabinet,
  CalendarRange,
  Check,
  Check as CheckIcon,
  CircleCheck as CheckCircle2,
  CircleCheck,
  CircleCheck as CircleCheckIcon,
  ChevronDown,
  ChevronDown as ChevronDownIcon,
  ChevronLeft,
  ChevronRight,
  ChevronRight as ChevronRightIcon,
  ChevronUp,
  ChevronUp as ChevronUpIcon,
  CircleAlert,
  CircleDashed,
  CircleDot,
  CircleSlash,
  Clock,
  Copy,
  Download,
  Eye,
  EyeOff,
  FileQuestionMark,
  Hammer,
  HardHat,
  Headset,
  House,
  ImagePlus,
  Inbox,
  Info as InfoIcon,
  Kanban,
  KeyRound,
  Languages,
  LayoutDashboard,
  LifeBuoy,
  ListChecks,
  List as ListView,
  LoaderCircle as Loader2,
  LoaderCircle as Loader2Icon,
  Lock,
  LogOut,
  Menu,
  Minus as MinusIcon,
  Moon,
  Ellipsis as MoreHorizontal,
  OctagonX,
  OctagonX as OctagonXIcon,
  Palette,
  CirclePause as PauseCircle,
  Pencil,
  CirclePlay as PlayCircle,
  Plus,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  SearchX,
  Send,
  Settings,
  ShieldMinus,
  ShieldPlus,
  SlidersHorizontal,
  Sun,
  Trash2,
  TrendingUp,
  TriangleAlert,
  TriangleAlert as TriangleAlertIcon,
  Upload,
  UserPlus,
  UserRound,
  Users,
  Wallet,
  X,
  X as XIcon,
} from "lucide-svelte";
